# Generated by Django 6.0.2 on 2026-02-19 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complexity_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(verbose_name='Ширина (см)')),
                ('height', models.FloatField(verbose_name='Высота(см)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за работу')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='gallery.artistprofile')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.tattoostyle')),
            ],
        ),
    ]
