# Generated by Django 6.0.2 on 2026-02-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название эскиза')),
                ('image', models.ImageField(upload_to='sketches/', verbose_name='Изображение')),
                ('detail_modifier', models.FloatField(default=1.0, verbose_name='Множитель детализации')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='gallery.artistprofile')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.tattoostyle')),
            ],
        ),
    ]
