# Generated by Django 6.0.2 on 2026-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_sketch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Место нанесения')),
                ('difficulty_factor', models.FloatField(default=1.0, verbose_name='Коэффициент сложности места')),
            ],
        ),
    ]
