# Generated by Django 6.0.2 on 2026-02-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_bodypart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='gallery.artistprofile')),
            ],
        ),
    ]
