# Generated by Django 6.0.2 on 2026-02-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_size', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.sketch')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.timeslot')),
            ],
        ),
    ]
