# Generated by Django 6.0.2 on 2026-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='calculated_size',
            field=models.CharField(max_length=50),
        ),
    ]
